on:
  push:
    branches:
      - main
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: 🔨 Build Project
        run: |
          npm install --prefix ./starot
          npm run build --prefix ./starot

      - name: 📂 Check build directory
        run: |
          if [ ! -d "./starot/dist" ]; then
            echo "Build directory not found!"
            exit 1
          fi

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.GIT_CPANEL_REACT_SERVER }}
          username: ${{ secrets.GIT_CPANEL_REACT_USER }}
          password: ${{ secrets.GIT_CPANEL_REACT_PWD }}
          protocol: ${{ secrets.GIT_CPANEL_REACT_PROTOCOL }}
          local-dir: ./starot/dist
